package gseproject.grid;

/**
 * 
 * @author	Steffen
 * @version	2016-11-17
 */
public enum SpaceType {
	
	NO_TRACK,
	TRACK,
	ROBOT,
	SOURCE_PALETTE,
	GOAL_PALETTE,
	PAINTING_STATION,
	PAINTING_STATION_TRANSPORT,
	PAINTING_STATION_WORKSPACE,
	CLEANING_STATION,
	CLEANING_STATION_TRANSPORT,
	CLEANING_STATION_WORKSPACE
}
