package gseproject.core.grid;

public enum SpaceType {
	NO_TRACK,
	DEFAULT,
	PALETTE_SOURCE,
	PALETTE_GOAL,
	CLEAN_TRANSPORT,
	CLEAN_WORK,
	PAINT_TRANSPORT,
	CLEANING_STATION_TRANSPORT,
	CLEANING_STATION_WORKSPACE,
	PAINTING_STATION_TRANSPORT,
	PAINTING_STATION,
	PAINTING_STATION_WORKSPACE,
	CLEANING_STATION,
	PAINT_WORK,
	TRACK
}
