package gseproject.core.grid;

public enum SpaceType {
	NO_TRACK,
	TRACK,
	PALETTE_SOURCE,
	PALETTE_GOAL,
	PAINT_TRANSPORT,
	CLEANING_STATION,
	CLEANING_STATION_TRANSPORT,
	CLEANING_STATION_WORKSPACE,
	PAINTING_STATION,
	PAINTING_STATION_TRANSPORT,
	PAINTING_STATION_WORKSPACE,
}
