/*****************************************************************
JADE - Java Agent DEvelopment Framework is a framework to develop
multi-agent systems in compliance with the FIPA specifications.
Copyright (C) 2000 CSELT S.p.A. 

GNU Lesser General Public License

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation, 
version 2.1 of the License. 

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the
Free Software Foundation, Inc., 59 Temple Place - Suite 330,
Boston, MA  02111-1307, USA.
*****************************************************************/

package test.common.testSuite.gui;

import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;

/**
 * @author Alessandro Negri - AOTLab UniPR
 * @author Matteo Bisi - UniPR
 * @author Yuri Ferrari - UniPR
 * @author Rossano Vitulli - UniPR
 * @version $Date: December 2003
 */
public class CounterPanel extends javax.swing.JPanel implements java.io.Serializable {
    
    /** Creates new form CounterPanel */
    public CounterPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        fNumberOfRuns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fNumberOfPassed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fNumberOfFailed = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fTimeElapsed = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        setMaximumSize(fNumberOfRuns.getPreferredSize());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Executed:  ");
        jLabel1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

        fNumberOfRuns.setColumns(5);
        fNumberOfRuns.setEditable(false);
        fNumberOfRuns.setFont(new java.awt.Font("Dialog", 1, 12));
        fNumberOfRuns.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fNumberOfRuns.setText("0 / 0");
        fNumberOfRuns.setToolTipText("Number of tests already runned");
        fNumberOfRuns.setBorder(null);
        fNumberOfRuns.setMaximumSize(fNumberOfRuns.getPreferredSize());
        fNumberOfRuns.setMinimumSize(fNumberOfRuns.getPreferredSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(fNumberOfRuns, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Passed:  ");
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(jLabel2, gridBagConstraints);

        fNumberOfPassed.setColumns(4);
        fNumberOfPassed.setEditable(false);
        fNumberOfPassed.setFont(new java.awt.Font("Dialog", 1, 12));
        fNumberOfPassed.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fNumberOfPassed.setText("0");
        fNumberOfPassed.setToolTipText("Number of tests succeded");
        fNumberOfPassed.setBorder(null);
        fNumberOfPassed.setMaximumSize(fNumberOfPassed.getPreferredSize());
        fNumberOfPassed.setMinimumSize(fNumberOfPassed.getPreferredSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        add(fNumberOfPassed, gridBagConstraints);

        jLabel3.setText("Failed:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(jLabel3, gridBagConstraints);

        fNumberOfFailed.setColumns(4);
        fNumberOfFailed.setEditable(false);
        fNumberOfFailed.setFont(new java.awt.Font("Dialog", 1, 12));
        fNumberOfFailed.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fNumberOfFailed.setText("0");
        fNumberOfFailed.setToolTipText("Number of tests failed");
        fNumberOfFailed.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        add(fNumberOfFailed, gridBagConstraints);

        jLabel4.setText("Elapsed time:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        add(jLabel4, gridBagConstraints);

        fTimeElapsed.setColumns(9);
        fTimeElapsed.setEditable(false);
        fTimeElapsed.setFont(new java.awt.Font("Dialog", 1, 12));
        fTimeElapsed.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fTimeElapsed.setText("0,0 seconds");
        fTimeElapsed.setToolTipText("Tests time elapsed");
        fTimeElapsed.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(fTimeElapsed, gridBagConstraints);

    }//GEN-END:initComponents

    /** Getter for property fTotalRuns.
     * @return Value of property fTotalRuns.
     *
     */
    public int getFTotalRuns() {
        return fTotalRuns;
    }    

    /** Setter for property fTotalRuns.
     * @param value New value of property fTotalRuns.
     *
     */
    public void setFTotalRuns(int value) {
        fTotalRuns = value;
        setRunsValue();
    }
    
    /** Set the number of tests already runned */
    public void setRunsCount(int value) {
        testsRuns = value;
        setRunsValue();
    }
    
    /** Get the number of tests already runned */
    public int getRunsCount() {
        return testsRuns;
    }
    
    /** Set the number of tests passed */
    public void setPassedCount(int value) {
        testsPassed = value;
        setLabelValue(fNumberOfPassed, testsPassed);
    }
    
    /** Get the number of tests passed */
    public int getPassedCount() {
        return testsPassed;
    }
    
    /** Set the number of tests failed */
    public void setFailedCount(int value) {
        testsFailed = value;
        setLabelValue(fNumberOfFailed, testsFailed);
    }
    
    /** Get the number of tests failed */
    public int getFailedCount() {
        return testsFailed;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fNumberOfFailed;
    private javax.swing.JTextField fNumberOfPassed;
    private javax.swing.JTextField fNumberOfRuns;
    private javax.swing.JTextField fTimeElapsed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
   
    private int fTotalRuns = 0;
    private int testsRuns = 0;
    private int testsPassed = 0;
    private int testsFailed = 0;
    
    public void reset(boolean bTotal, boolean RunAll) {
        if (!bTotal)
            fTotalRuns = 0;
        testsRuns = 0;
        testsPassed = 0;
        testsFailed = 0;
        
        updateGUI(bTotal, RunAll);
    }
    
    public void setRunsValue() {
        fNumberOfRuns.setText(Integer.toString(testsRuns) + " / " + fTotalRuns);
    }
    
    public void setElapsedTime(long value, boolean runAll) {
        int mins = 0, secs = 0; 
        double mills = 0.000;
        String testo = "";
        secs = (int)((double)value/1000);
        mills = (double)((double)value % 1000);
        
        if(secs > 59) {
            mins = (int)((double)secs/60);     
            secs -= (60 * mins);
        }    
               
        if(mins == 0)                       
            testo = NumberFormat.getInstance().format((int)secs);                    
        else
            if(secs < 10)   testo = NumberFormat.getInstance().format((int)mins) +
                                    " : " + "0" + NumberFormat.getInstance().format((int)secs);                                    
            else            testo = NumberFormat.getInstance().format((int)mins) +
                                    " : " + NumberFormat.getInstance().format((int)secs);

        if(!runAll)
            testo += "." + NumberFormat.getInstance().format((double)mills);            
            
        fTimeElapsed.setText( testo + " secs");                
    }
        
    private void setLabelValue(JTextField label, int value) {
        label.setText(Integer.toString(value));
    }
    
    private void updateGUI(boolean NotbTotal, boolean RunAll) {    
        fNumberOfRuns.setText("0 / " + Integer.toString(fTotalRuns));
        fNumberOfPassed.setText("0");
        fNumberOfFailed.setText("0");
        if(!RunAll)
            fTimeElapsed.setText("0,0 seconds");    
    } 
    
    private void updateGUI() {
        fNumberOfRuns.setText("0 / " + Integer.toString(fTotalRuns));
        fNumberOfPassed.setText("0");
        fNumberOfFailed.setText("0");        
        fTimeElapsed.setText("0,0 seconds");        
    }
}
