/*****************************************************************
JADE - Java Agent DEvelopment Framework is a framework to develop
multi-agent systems in compliance with the FIPA specifications.
Copyright (C) 2000 CSELT S.p.A. 

GNU Lesser General Public License

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation, 
version 2.1 of the License. 

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the
Free Software Foundation, Inc., 59 Temple Place - Suite 330,
Boston, MA  02111-1307, USA.
*****************************************************************/

package test.common.testSuite.gui;

/**
 * @author  Alessandro Negri - UniPR
 * @version $Date: 2004-03-23 16:57:48 +0100 (mar, 23 mar 2004) $ $Revision: 350 $
 */
public class ExitDialog extends javax.swing.JDialog {

    public static final int CANCEL = 0;
    public static final int EXIT_TEST_SUITE = 1;
    public static final int SHUT_DOWN = 2;

    private int exitValue = CANCEL;
    
    /** Creates new form ExitDialog */
    public ExitDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }
    
    public int getExitValue() {
    	return exitValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButtonJADE = new javax.swing.JButton();
        jButtonFramework = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jExitIcon = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("EXIT");
        setModal(true);
        setName("exitDlg");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dispose();
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Exiting Test Suite Framework ...");
        jTextField1.setBorder(null);
        jTextField1.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        getContentPane().add(jTextField1, gridBagConstraints);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Dialog", 3, 12));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Select the action you want to perform");
        jTextField2.setBorder(null);
        jTextField2.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(jTextField2, gridBagConstraints);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Dialog", 3, 12));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("or click Cancel to abort");
        jTextField3.setBorder(null);
        jTextField3.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 20, 0);
        getContentPane().add(jTextField3, gridBagConstraints);

        jButtonJADE.setMnemonic('J');
        jButtonJADE.setText("Shutdown JADE");
        jButtonJADE.setToolTipText("Shutdown JADE");
        jButtonJADE.setMaximumSize(new java.awt.Dimension(159, 26));
        jButtonJADE.setMinimumSize(new java.awt.Dimension(159, 26));
        jButtonJADE.setNextFocusableComponent(jButtonCancel);
        jButtonJADE.setPreferredSize(new java.awt.Dimension(159, 26));
        jButtonJADE.setSelected(true);
        jButtonJADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJADEActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 10, 2);
        getContentPane().add(jButtonJADE, gridBagConstraints);

        jButtonFramework.setMnemonic('F');
        jButtonFramework.setText("Exit Test Suite");
        jButtonFramework.setToolTipText("Close the Test Suite without shutting down JADE");
        jButtonFramework.setNextFocusableComponent(jButtonJADE);
        jButtonFramework.setRequestFocusEnabled(false);
        jButtonFramework.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFrameworkActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 2);
        getContentPane().add(jButtonFramework, gridBagConstraints);

        jButtonCancel.setMnemonic('C');
        jButtonCancel.setText("Cancel");
        jButtonCancel.setToolTipText("Return to Test Suite Framework");
        jButtonCancel.setNextFocusableComponent(jButtonFramework);
        jButtonCancel.setRequestFocusEnabled(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 10, 5);
        getContentPane().add(jButtonCancel, gridBagConstraints);

        jExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/common/testSuite/gui/images/exit.png")));
        jExitIcon.setBorder(null);
        jExitIcon.setDefaultCapable(false);
        jExitIcon.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jExitIcon, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void jButtonJADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJADEActionPerformed
        // not yet implemented
        javax.swing.JOptionPane.showMessageDialog(this, "Not yet implemented !!!", "ToDo", javax.swing.JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jButtonJADEActionPerformed

    private void jButtonFrameworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFrameworkActionPerformed
        exitValue = EXIT_TEST_SUITE;
        dispose();
    }//GEN-LAST:event_jButtonFrameworkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        exitValue = CANCEL;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFramework;
    private javax.swing.JButton jButtonJADE;
    private javax.swing.JButton jExitIcon;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
