/*****************************************************************
JADE - Java Agent DEvelopment Framework is a framework to develop
multi-agent systems in compliance with the FIPA specifications.
Copyright (C) 2000 CSELT S.p.A. 

GNU Lesser General Public License

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation, 
version 2.1 of the License. 

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the
Free Software Foundation, Inc., 59 Temple Place - Suite 330,
Boston, MA  02111-1307, USA.
*****************************************************************/

package test.common;

import java.io.*;

/**
 * @author Matteo Bisi - UniPR
 * @author Yuri Ferrari - UniPR
 * @author Rossano Vitulli - UniPR
 * @version $Date: December 2003
 */

/**
 * This class contains methods to log informations into HTML document.
 */
public class HTMLManager {

    private static String headString;
    private static String indexString;
    private static String indexClosingString;
    private static String bodyString;
    private static String closingString;

    private static int blockCounter = 0;

    /** Creates a new instance of htmlManager */
    public static void init(String fileName) {
        headString =    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\"\"http://www.w3.org/TR/REC-html40/loose.dtd\">\n"+
                        "<!-- This document was automatically generated by Test Suite Framework\n"+
                        "  -- Authors: Matteo Bisi     - uniPR - Italy\n"+
                        "  --          Yuri Ferrari    - uniPR - Italy\n"+
                        "  --          Rossano Vitulli - uniPR - Italy\n"+
                        "  -->\n\n"+
                        "<HTML>\n\n"+
                        "<HEAD>\n"+
                        "<TITLE>"+fileName+"</TITLE>\n"+
                        "</HEAD>\n\n"+
                        "<BODY BGCOLOR=\"white\">\n"+
                        "<TABLE BORDER=\"0\" CELLPADDING=\"3\" CELLSPACING=\"0\">\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=\"#CCCCFF\" CLASS=\"NavBarCell1\"><B>"+fileName+"</B></TD>\n"+
                        "  </TR>\n"+
                        "</TABLE>\n"+
                        "<P>\n\n\n";

        indexString =   "<TABLE ALIGN=\"center\" BORDER=\"0\" WIDTH=\"100%\" CELLPADDING=\"1\" CELLSPACING=\"0\">\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=#AEAEFF><FONT SIZE=\"+3\"><B>INDEX:</B></FONT></TD>\n"+
                        "  </TR>\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=#D0D0FF COLSPAN=\"2\"><FONT SIZE=\"-2\">CLICK ON THE DESIRED EXECUTION'S LINK TO SEE MORE DETAILS</FONT></TD>\n"+
                        "  </TR>\n"+
                        "</TABLE>\n"+
                        "<P>\n"+
                        "<TABLE ALIGN=\"center\" BORDER=\"0\" WIDTH=\"95%\" CELLPADDING=\"5\" CELLSPACING=\"0\">\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=\"#EEEEFF\" WIDTH=\"200\"><B>Execution mode</B></TD>\n"+
                        "    <TD BGCOLOR=\"#EEEEFF\"><B>Tester Agent</B></TD>\n"+
                        "    <TD BGCOLOR=\"#EEEEFF\" WIDTH=\"200\"><B>Summary</B></TD>\n"+
                        "  </TR>\n";
        
        indexClosingString = "</TABLE>\n";
        
        bodyString =    "\n\n<P>\n"+
                        "<TABLE BORDER=\"0\" WIDTH=\"100%\" CELLPADDING=\"1\" CELLSPACING=\"0\">\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=#AEAEFF><FONT SIZE =\"+3\"><B>BODY:</B></FONT></TD>\n"+
                        "  </TR>\n"+
                        "  <TR>\n"+
                        "    <TD BGCOLOR=#D0D0FF COLSPAN=\"2\"><FONT SIZE=\"-2\">LOGGED SESSION</FONT></TD>\n"+
                        "  </TR>\n"+
                        "</TABLE>\n"+
                        "<P>\n\n\n";

        closingString = "\n\n</BODY>\n</HTML>\n";
    }
    
    /** Add string s to the content of indexString */
    public static void addIndex(String s) {
        indexString += s;
    }
    
    /** Add string s to the content of bodyString */
    public static void addBody(String s) {
        bodyString += s;
    }
    
    /** Add string s to the content of closingString */
    public static void setClosing(String s) {
        closingString = s;
    }

    /** Write all strings (headString + indexString + indexClosingString + bodyString 
        + closingString) on the HTML file */
    public static void buildFile(PrintStream out) {
        out.println(headString + indexString + indexClosingString + bodyString + closingString);
    }

    /** Return a counter of the blocks in body section: each block identifies
        a Run or RunAll execution */
    public static int getBlockCounter() {
        return blockCounter;
    }
    
    /** Increments the counter of the blocks in body section */
    public static void incBlockCounter() {
        blockCounter++;
    }
}
